includes:
  - include/base.yaml
includes:
  - include/jobs/*.yaml

envs:
  DEMO_SOURCE: main
  BASE_ENV: "this is base env"
  TIME: $PIPELINE_TIMESTAMP

build_job:
  actions:
    - echo "build actions overridden by main config"
    - echo "timeout is inherited from include/base.yaml"

local_job:
  stage: test
  actions:
    - echo "local job defined in configs/include-demo.yaml"
    - echo "BASE_ENV = $BASE_ENV"
    - echo "TIME = $TIME"
