name: "test-pipeline"
version: "1.0.0"

envs:
  - "HELLO=world"

workdir: "D:\\"

stages:
  - build
  - test
  - deploy
  # - test

skips: # 可以是stage或job
  # - test
  - job5
  - job6

job1:
  stage: build
  actions:
    - echo "I am job1, $HELLO"
    - echo "I am in build stage"
    - sleep 5
    - echo "I am job1, slept for 5s"
  timeout: 2s
  allow_failure: yes

job2:
  stage: test
  actions:
    - echo "I am job2, $HELLO"
    - echo "I am in test stage"

job3:
  stage: deploy
  actions:
    - echo "I am job3, $HELLO"
    - echo "I am in deploy stage"

job4:
  stage: deploy
  actions:
    - echo "I am job4, $HELLO"
    - echo "I am in deploy stage"

job5:
  stage: deploy
  actions:
    - echo "I am job5, $HELLO"
    - echo "I am in deploy stage"

job6:
  stage: deploy
  actions:
    - echo "I am job6, $HELLO"
    - echo "I am in deploy stage"

job7:
  stage: deploy
  actions:
    - echo "I am job7, $HELLO"
    - echo "I am in deploy stage"