name: "test-pipeline"
version: "1.0.0"

envs:
  - "HELLO=world"
  - GOROOT=D:\Go\go:$GOROOT
  - "PING=PONG"
  - "PING=abc:$PING"
  - "PING=$PING:edf"
  - "MY_PWD=`pwd`"
  - "MY_TIMESTAMP=$(date +%s)"
  - "GET_PIPELINE_TIMESTAMP=$PIPELINE_TIMESTAMP"
  - "MY_INLINE_CMD=an apple a day,$(date +%s),keeps the `echo -n \"doctor\"` away"

workdir: "D:\\"

stages:
  - debug
  - build
  - test
  - deploy
  # - test

skips: # 可以是stage或job
  # - test
  - job5
  - job6

debug_job:
  stage: debug
  actions:
    - "echo \"builtin PIPELINE_NAME: $PIPELINE_NAME\""
    - "echo \"builtin PIPELINE_VERSION: $PIPELINE_VERSION\""
    - "echo \"builtin PIPELINE_TIMESTAMP: $PIPELINE_TIMESTAMP\""
    - "echo \"builtin PIPELINE_WORKDIR: $PIPELINE_WORKDIR\""
    - "echo \"builtin STAGE_NAME: $STAGE_NAME\""
    - "echo \"builtin JOB_NAME: $JOB_NAME\""
    - "echo \"builtin MY_PWD: $MY_PWD\""
    - "echo \"builtin MY_TIMESTAMP: $MY_TIMESTAMP\""
    - "echo \"builtin GET_PIPELINE_TIMESTAMP: $GET_PIPELINE_TIMESTAMP\""
    - "echo \"builtin MY_INLINE_CMD: $MY_INLINE_CMD\""
    - exit 1

job1:
  stage: build
  actions:
    - "echo \"job1 STAGE_NAME: $STAGE_NAME, JOB_NAME: $JOB_NAME\""
    - echo "I am job1, $HELLO"
    - echo "I am job1, $GOROOT"
    - echo "I am job1, $PING"
    - echo "I am in build stage"
    - sleep 5
    - echo "I am job1, slept for 5s"
  timeout: 2s
  allow_failure: yes

job2:
  stage: test
  actions:
    - |
      echo "job2 STAGE_NAME: $STAGE_NAME, JOB_NAME: $JOB_NAME" # 如果不使用下面的引号转义，就需要使用块标量语法，否则这里的冒号会导致解析错误
    # - "echo \"job2 STAGE_NAME: $STAGE_NAME, JOB_NAME: $JOB_NAME\""
    - echo "I am job2, $HELLO"
    - echo "I am in test stage"
    - "echo \"kv whoami: $USER\""
    - "echo \"kv gender: $GENDER\""
    - "echo \"flag male: $MALE\""
    - "echo \"flag female: $FEMALE\""

job3:
  stage: deploy
  actions:
    - "echo \"job3 STAGE_NAME: $STAGE_NAME, JOB_NAME: $JOB_NAME\""
    - echo "I am job3, $HELLO"
    - echo "I am in deploy stage"

job4:
  stage: deploy
  actions:
    - "echo \"job4 STAGE_NAME: $STAGE_NAME, JOB_NAME: $JOB_NAME\""
    - echo "I am job4, $HELLO"
    - echo "I am in deploy stage"

job5:
  stage: deploy
  actions:
    - "echo \"job5 STAGE_NAME: $STAGE_NAME, JOB_NAME: $JOB_NAME\""
    - echo "I am job5, $HELLO"
    - echo "I am in deploy stage"

job6:
  stage: deploy
  actions:
    - "echo \"job6 STAGE_NAME: $STAGE_NAME, JOB_NAME: $JOB_NAME\""
    - echo "I am job6, $HELLO"
    - echo "I am in deploy stage"

job7:
  stage: deploy
  actions:
    - "echo \"job7 STAGE_NAME: $STAGE_NAME, JOB_NAME: $JOB_NAME\""
    - echo "I am job7, $HELLO"
    - echo "I am in deploy stage"